jQuery(document).ready(function($){jQuery(document).on('click','.articles .pagination a',function(e){e.preventDefault();ab_scroll_top(180);let page=1;let href=jQuery(this).attr('href');if(href.length){page=parseInt(get_url_parameter(href,'page'));}
if(typeof href==="undefined"||href.length==0||page==1){href='';}
let tag_id=get_page_tag_id();let categoryId=get_active_tag_id();let search_type=get_search_type();let link=location.origin+location.pathname+href;ajax_get_posts(page,categoryId,false,search_type,tag_id);if(!tag_id){save_to_history(categoryId,page,link);}
jQuery('#articles__loadmore').attr('data-paged',page);if(page==parseInt(jQuery('#articles__loadmore').attr('data-max-page'))){jQuery('#articles__loadmore').remove();}})
jQuery(document).on('click','.category-menu__item a',function(e){e.preventDefault();let currentElement=jQuery(this);if(currentElement.parent().hasClass('category-menu__item--active'))return;jQuery('.search-posts__form input, .mobile-search__form input').val('');jQuery('.no-result-wrap').hide();if(jQuery(window).width()<=768){ab_scroll_top(110);}else{ab_scroll_top(180);}
jQuery('.mobile-category-popup').removeClass('mobile-category-popup--open');jQuery('.category-menu__item').removeClass('category-menu__item--active');currentElement.parent().addClass('category-menu__item--active');let tag_id=get_page_tag_id();let categoryId=get_active_tag_id();let categoryName=jQuery(this).text();let categoryCustomName=jQuery(this).attr('data-custom-name');let search_type=get_search_type();if(categoryCustomName!=''){categoryName=categoryCustomName;}
ajax_get_posts(1,categoryId,false,search_type,tag_id);jQuery('#articles__loadmore').attr('data-paged',1);let link=currentElement.attr('href');if(link.length&&link!=='#'){save_to_history(categoryId,1,link);updateHeroH1(categoryId,categoryName);}})
jQuery(document).on('click','#articles__loadmore',function(e){e.preventDefault();jQuery(this).prop('disabled',true);jQuery(this).find('.spinner-load').show();if(articlesLoading||window.matchMedia('(min-width: 769px)').matches){return;}
let categoryId=get_active_tag_id();let search_type=get_search_type();let data_max_page=jQuery(this).attr('data-max-pages');let max_num_pages=(data_max_page!=''&&data_max_page!=undefined)?parseInt(data_max_page):1;let paged=jQuery(this).attr('data-paged');let page=(paged!=''&&paged!=undefined)?parseInt(paged):1;ajax_get_posts(page,categoryId,true,search_type).done(()=>{jQuery(this).attr('data-paged',++page);if(paged==max_num_pages){jQuery(this).remove();return;}});})
window.addEventListener('popstate',()=>{if(jQuery('.portfolio-articles').length||jQuery('.blog-articles').length){window.location.href=location.href;}});})