var dotNetSliders=Array();jQuery(document).ready(function($){var more=$('a.project__more'),sliderText=more.eq(0).text(),mobProj=$('ul.projects__slider-mobile').find('.project__expand'),projText=mobProj.eq(0).text(),backLink=$('a#back__link');if(backLink.length){var _domain=document.domain,link=$('<a>',{href:document.referrer});if(link.get(0).hostname==_domain&&!!$.trim(document.referrer)){backLink.attr('href',"//"+document.referrer);}else{backLink.attr('href',"//"+document.domain);}}
$(".content__wrapper img").each(function(i,e){var el=$(e);var w=el.attr('width');var ow=el.prop('width');if(Number(w)!=Number(ow)){el.css('width',Number(w));}});mobProj.on('click',function(e){e.preventDefault();var $this=$(this),$text=$this.text();if($this.prev('.project__more-info').is('.active')){$('html, body').animate({scrollTop:$this.parents('.projects__item').offset().top-70},500);}
$this.toggleClass('collapsed').text($text==projText?'HIDE INFO':projText).prev('.project__more-info').toggleClass('active');});var expandListItem=$('.healthcare-industry__block-wrap');function expandCarousel(e){e.preventDefault();e.stopPropagation();var _self=$(this);$('.healthcare-industry__block-wrap.active').not(_self).removeClass('active');$(_self).toggleClass('active');}
function resizeHandle(){if($(window).width()>767){$('.dropdown-toggle').attr('data-toggle','');}else{$('.dropdown-toggle').attr('data-toggle','dropdown');}
if($(window).width()>991){expandListItem.off('click').removeClass('active');}else{expandListItem.off('click').on('click',expandCarousel);}}
resizeHandle();$(window).on('resize',resizeHandle);$.fn.almComplete=function(alm){if($('.twitter').length){$('.twitter').sharrre({share:{twitter:true},enableHover:false,enableTracking:true,click:function(api,options){api.simulateClick();api.openPopup('twitter');}});}
if($('.facebook').length){$('.facebook').sharrre({share:{facebook:true},enableHover:false,enableTracking:true,click:function(api,options){api.simulateClick();api.openPopup('facebook');}});}
if($('.googlePlus').length){$('.googlePlus').sharrre({share:{googlePlus:true},enableHover:false,enableTracking:true,click:function(api,options){api.simulateClick();api.openPopup('googlePlus');}});}
if($('.linkedin').length){$('.linkedin').sharrre({share:{linkedin:true},enableHover:false,enableTracking:true,click:function(api,options){api.simulateClick();api.openPopup('linkedin');}});}
if($('.pinterest').length){$('.pinterest').sharrre({share:{pinterest:true},enableHover:false,enableTracking:true,buttons:{pinterest:{}},click:function(api,options){options.buttons.pinterest.description=$(api.element).data('text');options.buttons.pinterest.media=$(api.element).data('media');options.buttons.pinterest.url=$(api.element).data('url');api.simulateClick();api.openPopup('pinterest');}});}};if($('.dot_net_projects__slider').length){$('.dot_net_projects__slider').each(function(){var sliderName=$(this).data('slider');dotNetSliders[sliderName]=$(this).bxSlider({adaptiveHeight:true,mode:'fade',captions:false,infiniteLoop:true,easing:'linear',pager:true,speed:2000,auto:true,pause:7000,preventDefaultSwipeX:true,preventDefaultSwipeY:false,onSlideBefore:function($slide,curIndex,nextIndex){$('.panel-collapse.in').collapse('hide');more.not('.collapsed').addClass('collapsed').text(sliderText);}});});}
$('#technologies').on('show.bs.collapse',function(e){$(this).find('.panel').removeClass('active');$(e.target).parents('.panel').addClass('active');}).on('hide.bs.collapse',function(e){$(e.target).parents('.panel').removeClass('active');}).children('.panel:first-child').addClass('active');var techBtn=$('a.technology__panel-btn'),techBtnText=$(techBtn.get(0)).text();techBtn.on('click',function(e){e.preventDefault();var $this=$(this),$text=$this.text();if($this.siblings('ul').is('.active')){$('html, body').animate({scrollTop:$this.siblings('h3').offset().top-70},500);}
$this.text($text==techBtnText?'HIDE INFO':techBtnText).prev('ul').toggleClass('active');});var imageHover=$('[data-hover]');if(imageHover.length){imageHover.each(function(i,el){$(el).attr('onmouseout',"this.src = '"+$(el).attr('src')+"'").attr('onmouseover',"this.src = '"+$(el).data('hover')+"'");});}
more.on('click',function(e){var $this=$(this),$text=$this.text();$this.addClass('ab_show_more_active');$this.text($text==sliderText?'HIDE INFO':sliderText);});var listBtn=$('.list__expand-btn'),listBtnText=listBtn.eq(0).text();listBtn.on('click',function(e){e.preventDefault();var $this=$(this),$text=$this.text();if($this.prev('ul').is('.active')){$('html, body').animate({scrollTop:$this.prev('ul').offset().top-140},500);}
$this.text($text==listBtnText?'HIDE':listBtnText).prev('ul').toggleClass('active');});});