jQuery(document).ready(function($){jQuery(document).on('keypress','.gform_wrapper',function(event){let code=event.keyCode||event.which;if(code===13&&!jQuery(event.target).is('textarea,input[type="submit"]')){event.preventDefault();return false;}});if(jQuery('.block-with-tabs__items').length&&jQuery(window).width()>576){$(".block-with-tabs__item").not(":first").hide();$(".block-with-tabs__items .block-with-tabs__tab-wrap").click(function(){$(".block-with-tabs__items .block-with-tabs__tab-wrap").removeClass("block-with-tabs__tab--active").eq($(this).index()).addClass("block-with-tabs__tab--active");$(".block-with-tabs__item").hide().eq($(this).index()).fadeIn()}).eq(0).addClass("block-with-tabs__tab--active");}
if(jQuery('.block-with-tabs__items').length){jQuery(document).on('click','.block-with-tabs__tab',function(e){if(jQuery(window).width()>576)return;e.preventDefault();jQuery(this).toggleClass('block-with-tabs__tab--open');jQuery(this).find('.block-with-tabs__accordion-btn').toggleClass('rotate-180');jQuery(this).next().slideToggle();})
jQuery(window).on('resize',function(){if(jQuery(window).width()>576){jQuery('.block-with-tabs__mob-item').slideUp().hide();jQuery('.block-with-tabs__accordion-btn').removeClass('rotate-180');}});}
if(jQuery('.block-reviews2__items').length){jQuery('.block-reviews2__items').slick({'autoplay':true,'autoplaySpeed':5000,'infinite':true,'dots':true,'arrows':false,'fade':true,'adaptiveHeight':true});}
if(jQuery('.block-with-gallery').length){jQuery('.block-with-gallery__item.slider').each(function(){jQuery(this).slick({'autoplay':true,'autoplaySpeed':getRandom(4000,10000),'speed':600,'infinite':true,'dots':false,'arrows':false,'fade':true,'adaptiveHeight':false,'centerMode':true,'centerPadding':0});});Fancybox.bind("[data-fancybox]",{});}
function getRandom(min,max){return Math.random()*(max-min)+min;}
if(jQuery('.styling-first-word ').length){addClassToFirstWord();}
jQuery(document).on("click",'a.ab_scrollTo, a[href^="#"]',function(e){let id=jQuery(this).attr('href');if(!id||id==='#')return;if(jQuery(id).length){e.preventDefault();let offsetTop=jQuery(id).offset().top-64;let top=jQuery('.ab-top-floating-panel').length?offsetTop-64:offsetTop;jQuery('html, body').animate({scrollTop:top},500);}});jQuery(document).on('click','.mobile-search__open, .portfolio-category-menu__open-btn',function(e){e.preventDefault();jQuery('.mobile-category-popup').addClass('mobile-category-popup--open');});jQuery(document).on('click','.mobile-category-popup__close',function(e){e.preventDefault();jQuery(this).parents('.mobile-category-popup').removeClass('mobile-category-popup--open');});jQuery(document).on('click','.mobile-category-popup__item',function(e){jQuery(this).parents('.mobile-category-popup').removeClass('mobile-category-popup--open');});if(jQuery('#blob3').length){setTimeout(function(){renderLiveBlob('#blob3');},2500);jQuery(window).on('resize',function(){renderLiveBlob('#blob3');});}
if(jQuery('.search__tab').length){jQuery(document).on('click','.search__tab a',function(e){e.preventDefault();jQuery('.search__tab').removeClass('search__tab--active');jQuery(this).parent().addClass('search__tab--active');})}
if(jQuery('.text-with-blobs__blobs #blob_n1').length){setTimeout(function(){renderLiveBlob('.text-with-blobs__blobs #blob_n1',16,0.65,1,0.00001,true);if(jQuery(window).width()>768){renderLiveBlob('.text-with-blobs__blobs #blob_n2',16,0.65,1,0.000012);}else{jQuery('.text-with-blobs__blobs #blob_n2 canvas').remove();}},3000);jQuery(window).on('resize',function(){renderLiveBlob('.text-with-blobs__blobs #blob_n1',16,0.65,1,0.00001,true);if(jQuery(window).width()>768){renderLiveBlob('.text-with-blobs__blobs #blob_n2',16,0.65,1,0.000012);}});}
if(jQuery('.big-content-slider__items').length){const big_content_slider=document.querySelector('.big-content-slider__items');let isDown=false;let startX;let scrollLeft;big_content_slider.addEventListener('mousedown',(e)=>{isDown=true;big_content_slider.classList.add('active');startX=e.pageX-big_content_slider.offsetLeft;scrollLeft=big_content_slider.scrollLeft;});big_content_slider.addEventListener('mouseleave',()=>{isDown=false;big_content_slider.classList.remove('active');});big_content_slider.addEventListener('mouseup',()=>{isDown=false;big_content_slider.classList.remove('active');});big_content_slider.addEventListener('mousemove',(e)=>{if(!isDown)return;e.preventDefault();const x=e.pageX-big_content_slider.offsetLeft;const walk=(x-startX)*1.25;big_content_slider.scrollLeft=scrollLeft-walk;});}
if(jQuery('.ab_youtube_video').length){const videos=document.querySelectorAll('.ab_youtube_video');let generateUrl=function(id){let query='?rel=0&showinfo=0&autoplay=1';return'https://www.youtube.com/embed/'+id+query;};let createIframe=function(id){let iframe=document.createElement('iframe');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay; encrypted-media');iframe.setAttribute('src',generateUrl(id));return iframe;};videos.forEach((el)=>{let videoHref=el.getAttribute('data-video');let videoId=getParameterByName('v',videoHref);let img=el.querySelector('img');if(img!==null){let youtubeImgSrc='https://i.ytimg.com/vi/'+videoId+'/maxresdefault.jpg';img.setAttribute('src',youtubeImgSrc);}
el.addEventListener('click',(e)=>{e.preventDefault();let iframe=createIframe(videoId);el.querySelector('img').remove();el.querySelector('a').remove();el.appendChild(iframe);});});}
const blockHeroPage2Title=jQuery('.block-with-hero-page2__title');if(blockHeroPage2Title.length){autoShrinkFont(blockHeroPage2Title[0],30,83);jQuery(window).on('resize',function(){autoShrinkFont(blockHeroPage2Title[0],30,83);});}
jQuery(document).on('click','.author-open-modal',function(e){e.preventDefault();const popupID=jQuery(this).attr('href');if(jQuery(popupID).length==0)return;jQuery(popupID).removeClass('hidden');jQuery('body').addClass('overflow-hidden');});jQuery(document).on('click','.popup-author__close, .popup-author__overlay',function(e){e.preventDefault();jQuery(this).closest('.popup-author').addClass('hidden');jQuery('body').removeClass('overflow-hidden');});function getParameterByName(name,url=window.location.href){name=name.replace(/[\[\]]/g,'\\$&');var regex=new RegExp('[?&]'+name+'(=([^&#]*)|&|#|$)'),results=regex.exec(url);if(!results)return null;if(!results[2])return'';return decodeURIComponent(results[2].replace(/\+/g,' '));}
function autoShrinkFont(el,minFont=10,maxFont=36){let fontSize=maxFont;el.style.fontSize=fontSize+'px';const hasOverflow=()=>el.scrollWidth>el.clientWidth;while(fontSize>minFont&&hasOverflow()){fontSize--;el.style.fontSize=fontSize+'px';el.style.lineHeight=(fontSize+10)+'px';}}});