var skeleton_html='<a href="#" class="articles__item skeleton__item group max-w-[320px] xl:max-w-[273px] bg-white font-gilroy transition-all no-underline float-left mb-[40px] hover:no-underline focus:no-underline lg:max-w-full md:w-full" style="order: 999;">'+'<div class="skeleton-item-wrap">'+'<div class="skeleton-shimmer"><div class="_2iwy"></div><div class="_2iw2"></div><div class="_2iwz"></div><div class="_2iw-"></div>'+'<div class="_2iw_"></div><div class="_2ix0"></div><div class="_2vl"></div><div class="_2vr"></div>'+'<div class="_2hd"></div><div class="_2ix1"></div><div class="_2hdb"></div>'+'</div>'+'</div>'+'</a>';function addClassToFirstWord(){let first_word_class='first-word';let el=jQuery('.styling-first-word');el.each(function(){let string=jQuery(this).html();let first_word=string.split(" ");let html="<span class="+first_word_class+">".concat(first_word[0],"</span>")+"&#32;"+string.substr(string.indexOf(" ")+1);jQuery(this).html(html);})}
function removeArticlesItemsWrapper(return_block=false){if(jQuery(window).width()<=768){jQuery('.articles__items .articles__col').each(function(i,el){jQuery(this).parent().append(jQuery(this).html());jQuery(this).remove();});if(return_block)return jQuery('#articles__items').html();}}
function renderLiveBlob(canvasWrapId,speedSlider=16,spikesSlider=0.65,processingSlider=1,timeKoef=0.00001,isBlue=false){const canvas=document.querySelector(`${canvasWrapId} canvas`);if(!canvas||canvas._blobInstance){return canvas?._blobInstance||null;}
const width=canvas.clientWidth||canvas.width;const height=canvas.clientHeight||canvas.height;if(!width||!height){return null;}
const isMobile=window.matchMedia('(max-width: 768px)').matches;const segments=isMobile?32:48;const targetFps=isMobile?24:30;const frameInterval=1000/targetFps;const pixelRatio=Math.min(window.devicePixelRatio||1,2);const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(pixelRatio);renderer.setSize(width,height,false);const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(30,width/height,0.1,1000);camera.position.z=5;const geometry=new THREE.SphereGeometry(0.8,segments,segments);const baseVertices=geometry.vertices.map((vertex)=>vertex.clone());const material=new THREE.MeshPhongMaterial({color:isBlue?0x00B4FF:0xE4ECFA,shininess:80});const topColor=isBlue?0x00B4FF:0xFFFFFF;const lightTop=new THREE.DirectionalLight(topColor,0.7);lightTop.position.set(0,5,2);const lightBottom=new THREE.DirectionalLight(topColor,0.25);lightBottom.position.set(0,-5,4);const ambientLight=new THREE.AmbientLight(0x798296,1);const sphere=new THREE.Mesh(geometry,material);scene.add(lightTop,lightBottom,ambientLight,sphere);const simplex=new SimplexNoise();let animationFrameId=null;let lastFrameTime=0;let running=false;let inViewport=true;let pageVisible=!document.hidden;let destroyed=false;function resize(){const newWidth=canvas.clientWidth;const newHeight=canvas.clientHeight;if(!newWidth||!newHeight){return;}
renderer.setSize(newWidth,newHeight,false);camera.aspect=newWidth/newHeight;camera.updateProjectionMatrix();}
function update(now){const time=now*timeKoef*speedSlider*Math.pow(processingSlider,3);const spikes=spikesSlider*processingSlider;for(let i=0;i<geometry.vertices.length;i++){const base=baseVertices[i];const vertex=geometry.vertices[i];const noise=simplex.noise3D(base.x*spikes,base.y*spikes,base.z*spikes+time);vertex.copy(base).multiplyScalar(1+0.3*noise);}
geometry.verticesNeedUpdate=true;geometry.computeVertexNormals();geometry.normalsNeedUpdate=true;}
function animate(now){if(!running||destroyed){return;}
animationFrameId=requestAnimationFrame(animate);if(now-lastFrameTime<frameInterval){return;}
lastFrameTime=now;update(now);renderer.render(scene,camera);}
function start(){if(running||destroyed||!inViewport||!pageVisible){return;}
running=true;lastFrameTime=0;animationFrameId=requestAnimationFrame(animate);}
function stop(){running=false;if(animationFrameId){cancelAnimationFrame(animationFrameId);animationFrameId=null;}}
function destroy(){if(destroyed){return;}
destroyed=true;stop();resizeObserver.disconnect();intersectionObserver.disconnect();document.removeEventListener('visibilitychange',onVisibilityChange);scene.remove(sphere);geometry.dispose();material.dispose();renderer.dispose();if(renderer.forceContextLoss){renderer.forceContextLoss();}
delete canvas._blobInstance;}
function onVisibilityChange(){pageVisible=!document.hidden;if(pageVisible){start();}else{stop();}}
const resizeObserver=new ResizeObserver(resize);const intersectionObserver=new IntersectionObserver(([entry])=>{inViewport=entry.isIntersecting;if(inViewport){start();}else{stop();}},{rootMargin:'100px 0px'});resizeObserver.observe(canvas);intersectionObserver.observe(canvas);document.addEventListener('visibilitychange',onVisibilityChange);const instance={start,stop,destroy,resize};canvas._blobInstance=instance;start();return instance;}
function abScrollTop(offset_top){jQuery('body,html').animate({scrollTop:offset_top},400);}
function isNumeric(value){return/^-?\d+$/.test(value);}
function saveToHistory(cat_id,page,link){if(cat_id==7&&page==1){history.pushState({cat_id:cat_id,page:1},'',location.origin+'/portfolio');return;}else if(cat_id==4&&page==1){history.pushState({cat_id:cat_id,page:1},'',location.origin+'/blog');return;}
if(page.length==0||page<=1){page=1;}
if(link.length&&cat_id>0){history.pushState({cat_id:cat_id,page:page},'',link);}}
function updateHeroH1(cat_id,text){const categoryHeroH1=jQuery('.blog-hero h1, .portfolio-hero h1');if(categoryHeroH1.length){if(cat_id==7){categoryHeroH1.text('portfolio');return;}else if(cat_id==4){categoryHeroH1.text('blog');return;}else{categoryHeroH1.text(text);}}}
var articlesRequest=null;var articlesLoading=false;function ajaxGetPosts(page=1,categoryId='',isMobile=false,searchType=false,tagId='',filters=null){if(articlesLoading){return jQuery.Deferred().reject('already_loading').promise();}
articlesLoading=true;const postType=jQuery('.articles').data('post_type');const searchParameter=postType==='search'?get_url_parameter(window.location.href,'s'):'';const $button=jQuery('#articles__loadmore');$button.prop('disabled',true).attr('aria-busy','true');$button.find('.spinner-load').show();toggleSkeletonLoader(true,isMobile);let requestData={action:'page_ajax_pagination',page_type:postType,paged:page,categoryId:categoryId,tagId:tagId,is_mobile:isMobile,search:searchParameter,search_type:searchType||''};if(postType==='portfolio'){if(!filters&&typeof getPortfolioFilters==='function'){filters=getPortfolioFilters();}
if(filters){requestData.filters=filters;if(filters.industry){requestData.categoryId=filters.industry;}
if(filters.search){requestData.search=filters.search;}}}
articlesRequest=jQuery.ajax({url:ajax_obj.ajaxurl,type:'POST',dataType:'json',timeout:10000,data:requestData});return articlesRequest.done((data)=>{if(!data?.status||typeof data.html!=='string'){throw new Error('Invalid AJAX response');}
toggleSkeletonLoader(false,isMobile,data);}).fail((xhr,status)=>{console.error('Posts loading failed:',status,xhr.responseText);toggleSkeletonLoader(false,isMobile);}).always(()=>{articlesLoading=false;articlesRequest=null;$button.prop('disabled',false).removeAttr('aria-busy');$button.find('.spinner-load').hide();});}
function toggleSkeletonLoader($enable=true,is_mobile=false,data=false){let articleItems=jQuery('#articles__items');let articleWrap=jQuery('.articles__wrap');let skeletonWrap=jQuery('.skeleton-wrap');if($enable){if(!is_mobile){skeletonWrap.show();articleItems.hide();}else{articleWrap.append(skeleton_html);}
return;}
if(!is_mobile){articleItems.html(data.html);articleItems.show();skeletonWrap.hide();}else{jQuery('#articles__items .skeleton__item').remove();articleWrap.append(data.html);}}
function get_active_tag_id(){let data_id=jQuery('.category-menu__item--active a').attr('data-id');return(data_id!=''&&data_id!=undefined)?parseInt(data_id):'';}
function get_page_tag_id(){let data_id=jQuery('.articles').data('tag_id');return(data_id!=''&&data_id!=undefined)?parseInt(data_id):'';}
function get_search_type(){let data_type=jQuery('.category-menu__item--active a').attr('data-type');return(data_type!=''&&data_type!=undefined)?data_type.replace(/(<([^>]+)>)/gi,''):'';}
function get_url_parameter(url_string,search_parameter){let url=new URL(url_string,window.location.protocol+'//'+window.location.hostname);let value=url.searchParams.get(search_parameter);return value;}
function getPostsByCatId(posts_wrap_object){if(!posts_wrap_object.length)
return false;let url_string=window.location.href;let url=new URL(url_string);var get_cat_id=url.searchParams.get("cat_id");let page=(url.searchParams.get("page")>=1)?url.searchParams.get("page"):1;let search_type=get_search_type();if(isNumeric(get_cat_id)){jQuery('.category-menu__item').removeClass('category-menu__item--active');jQuery('.category-menu__item a[data-id='+parseInt(get_cat_id)+']').parent().addClass('category-menu__item--active');ajaxGetPosts(parseInt(page),parseInt(get_cat_id),false,search_type);}else if(posts_wrap_object.length){get_cat_id=posts_wrap_object.data('cat-id');jQuery('.category-menu__item').removeClass('category-menu__item--active');jQuery('.category-menu__item a[data-id='+parseInt(get_cat_id)+']').parent().addClass('category-menu__item--active');ajaxGetPosts(parseInt(page),parseInt(get_cat_id),false,search_type);}}