jQuery(document).ready(function($){jQuery(document).on('click','.articles .pagination a',function(e){e.preventDefault();const isPortfolio=jQuery(this).closest('.articles').hasClass('portfolio-articles');let offsetTop=isPortfolio?portfolioPaginationOffsetTop():180;abScrollTop(offsetTop);let page=1;let href=jQuery(this).attr('href');if(href&&href.length){page=parseInt(get_url_parameter(href,'page'));}
if(typeof href==="undefined"||!href||href.length==0||isNaN(page)||page<1){page=1;href='';}
if(isPortfolio){let filters=typeof getPortfolioFilters==='function'?getPortfolioFilters():{};let categoryId=filters.industry||7;ajaxGetPosts(page,categoryId,false,false,'',filters);if(typeof updatePortfolioUrlParams==='function'){updatePortfolioUrlParams(filters,page);}}else{let tag_id=get_page_tag_id();let categoryId=get_active_tag_id();let search_type=get_search_type();let link=location.origin+location.pathname+href;ajaxGetPosts(page,categoryId,false,search_type,tag_id);if(!tag_id){saveToHistory(categoryId,page,link);}}
jQuery('#articles__loadmore').attr('data-paged',page);if(page==parseInt(jQuery('#articles__loadmore').attr('data-max-page'))){jQuery('#articles__loadmore').remove();}})
jQuery(document).on('click','.category-menu__item a',function(e){e.preventDefault();let currentElement=jQuery(this);if(currentElement.parent().hasClass('category-menu__item--active'))return;jQuery('.search-posts__form input, .mobile-search__form input').val('');jQuery('.no-result-wrap').hide();if(jQuery(window).width()<=768){abScrollTop(110);}else{abScrollTop(180);}
jQuery('.mobile-category-popup').removeClass('mobile-category-popup--open');jQuery('.category-menu__item').removeClass('category-menu__item--active');currentElement.parent().addClass('category-menu__item--active');let tag_id=get_page_tag_id();let categoryId=get_active_tag_id();let categoryName=jQuery(this).text();let categoryCustomName=jQuery(this).attr('data-custom-name');let search_type=get_search_type();if(categoryCustomName!=''){categoryName=categoryCustomName;}
ajaxGetPosts(1,categoryId,false,search_type,tag_id);jQuery('#articles__loadmore').attr('data-paged',1);let link=currentElement.attr('href');if(link.length&&link!=='#'){saveToHistory(categoryId,1,link);updateHeroH1(categoryId,categoryName);}})
jQuery(document).on('click','#articles__loadmore',function(e){e.preventDefault();jQuery(this).prop('disabled',true);jQuery(this).find('.spinner-load').show();if(articlesLoading||window.matchMedia('(min-width: 769px)').matches){return;}
const isPortfolio=jQuery(this).closest('.articles').hasClass('portfolio-articles');let filters=isPortfolio&&typeof getPortfolioFilters==='function'?getPortfolioFilters():null;let categoryId=isPortfolio?((filters&&filters.industry)?filters.industry:7):get_active_tag_id();let search_type=get_search_type();let data_max_page=jQuery(this).attr('data-max-pages');let max_num_pages=(data_max_page!=''&&data_max_page!=undefined)?parseInt(data_max_page):1;let paged=jQuery(this).attr('data-paged');let page=(paged!=''&&paged!=undefined)?parseInt(paged):1;ajaxGetPosts(page,categoryId,true,search_type,'',filters).done(()=>{jQuery(this).attr('data-paged',++page);if(paged==max_num_pages){jQuery(this).remove();return;}});})
window.addEventListener('popstate',()=>{if(jQuery('.portfolio-articles').length||jQuery('.blog-articles').length){window.location.href=location.href;}});})
function portfolioPaginationOffsetTop(){let offsetTop=180;const isPortfolio=jQuery(document).find('.articles.portfolio-articles');if(!isPortfolio)return offsetTop;const portfolioHero=jQuery('.portfolio-hero');const portfolioHeroHeight=portfolioHero.length>0?portfolioHero.outerHeight(true):0;const portfolioShowcases=jQuery('.portfolio-showcases');const portfolioShowcasesHeight=portfolioShowcases.length>0?portfolioShowcases.outerHeight(true):0;offsetTop=portfolioHeroHeight+portfolioShowcasesHeight;return offsetTop;}